# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx1200m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2

# AndroidX package structure
android.useAndroidX=true

# Non-transitive R class for faster build in Android Studio
android.nonTransitiveRClass=true

# Java toolchain path (Adoptium JDK 17)
org.gradle.java.home=C\:/Users/SIVA/.gradle/jdks/eclipse_adoptium-17-amd64-windows.2
