# Project-wide Gradle settings.

# Gradle JVM memory and encoding for Android Studio
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseG1GC

# AndroidX package structure
android.useAndroidX=true

# Non-transitive R class for faster build in Android Studio
android.nonTransitiveRClass=true

# Java 17 toolchain path
org.gradle.java.home=C\:/Users/SIVA/.gradle/jdks/eclipse_adoptium-17-amd64-windows.2
