# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true

# Non-transitive R class for faster build in Android Studio
android.nonTransitiveRClass=true

# Java toolchain path (Android Studio bundled JBR)
org.gradle.java.home=C\:/Program Files/Android/Android Studio/jbr
